<?php

namespace ContactBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findAllContactsASC(){
        $dql = 'SELECT c FROM ContactBookBundle:Contact c ORDER BY c.name ASC';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }
    
    public function findContactsByName($name){
        $dql = 'SELECT c FROM ContactBookBundle:Contact c WHERE c.name LIKE :name';
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('name', $name.'%');
        return $query->getResult();
    }
}
